name = "Modpack"
author = "Solariity & kapsikkum"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fa5ad780e2cc8b54f86f1c328fbfbb52409ee1bf132317bc67ece151d7593996"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.172"

[options]
acceptable-game-versions = []
