name = "Modpack"
author = "Solariity & kapsikkum"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c8df0fb876525806d10d0e6586bebb627fe6ab017a57befed6bf394c46d1b547"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.172"

[options]
acceptable-game-versions = []
